#!/bin/bash
thisdir=$(dirname $0)

rm -rf $thisdir/../build/*
xcodebuild -project $thisdir/../FinderExtension.xcodeproj -target AeroFSFinderExtension -configuration Debug clean install

if [ $? -ne 0 ]
then
    echo "ERROR: xcodebuild failed."
    exit 1
fi

echo "Moving to approot..."
rm -rf $thisdir/../../../../approot/AeroFSFinderExtension.osax
# cp -r is BAD, prefer cp -a or cp -R for OSX compatibility; man 1 cp
cp -a $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax $thisdir/../../../../approot

echo
echo "SUCCESS."
