#!/bin/bash
set -e

thisdir=$(dirname $0)

rm -rf $thisdir/../build/*
xcodebuild -project $thisdir/../FinderExtension.xcodeproj -target AeroFSFinderExtension -configuration Release clean install

if [ $? -ne 0 ]
then
    echo "ERROR: xcodebuild failed."
    exit 1
fi

echo "Looking for absolute paths hardcoded in the executable..."
error1=$(strings $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax/Contents/MacOS/AeroFSFinderExtension | grep -c /Users)
error2=$(strings $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax/Contents/Resources/finder_inject | grep -c /Users)

if [ $error1 -ne 0 ] || [ $error2 -ne 0 ]
then
    echo "ERROR: strings failed. Hard coded absolute paths exist in the executable..."
    exit 2
fi

echo "Signing code..."
codesign -f -s "Air Computing, Inc." $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax
if [ $? -ne 0 ] ; then
    echo "Codesigning failed.  Do you have the keys installed in your keychain?"
    exit 3
fi

echo "Moving to resource/client..."
rm -rf $thisdir/../../../../resource/client/osx/AeroFSFinderExtension.osax
# cp -r is BAD, prefer cp -a or cp -R for OSX compatibility; man 1 cp
cp -a $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax $thisdir/../../../../resource/client/osx

echo
echo "SUCCESS."
