name    'aerofs-logrotate'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'module for logrotate package and defined type for rotating logs'
description 'logrotate package with rotating log type'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
