#!/bin/bash

SUCCESS=TRUE

url()
{
    echo "Verifying $1"
    wget --timeout=10 --no-cache -q -O /dev/null $1
    CODE=$?
    if [ $CODE != 0 ]; then
        echo "Failure with url: $1 - wget returned $CODE"
        SUCCESS=FALSE
    fi
}

url-internal-ssl()
{
    echo "Verifying $1"
    wget --ca-certificate=/etc/ssl/certs/AeroFS_CA.pem --timeout=10 --no-cache -q -O /dev/null $1
    CODE=$?
    if [ $CODE != 0 ]; then
        echo "Failure with url: $1 - wget returned $CODE"
        SUCCESS=FALSE
    fi
}

port()
{
    echo "Verifying port $2 on $1"
    nc -z $1 $2 > /dev/null
    CODE=$?
    if [ $CODE != 0 ]; then
        echo "Failure with port $2 on $1 - nc returned $CODE"
        SUCCESS=FALSE
    fi
}

port verkehr.aerofs.com 443
port x.aerofs.com 443
port zephyr.aerofs.com 443
url https://aerofs.com/login
url https://sv.aerofs.com/sv_beta/sv
url-internal-ssl https://sp.aerofs.com/sp

if [ $SUCCESS == TRUE ]; then
    exit 0
else
    exit 1
fi
