#cloud-config

write_files:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      # Point to vpn.arrowfs.org
      DNS=172.16.0.83
  - path: /etc/systemd/system/docker.service.d/50-extra-options.conf
    content: |
      [Service]
      Environment='DOCKER_OPTS=--dns="172.17.42.1" --dns="172.16.0.83"'
