#!/bin/bash

# usage: $0 <service> <probe> <probe_specific_args>...

SERVICE=$1
PROBE=$2
shift 2

if [ x"$SERVICE" == x ]; then
    echo bad arguments
    exit 1
fi

SCRIPT=`readlink -f "$0"`
SCRIPT=`dirname "$SCRIPT"`/probes/$PROBE

TRIES=3
for i in `seq 1 $TRIES`; do
    /bin/bash "$SCRIPT" $@
    RET=$?
    if [ $RET == 0 ]; then
        exit 0
    elif [ $i != $TRIES ]; then
        sleep 2
    else
        ARGS="$@"
        TITLE="$PROBE returned $RET: $ARGS"
        echo sending alert \"$TITLE\"
        echo " " | mail $SERVICE@aerofs.pagerduty.com -s "$TITLE"
        exit 1
    fi
done
