#!/bin/bash

# Make scripts executable
sudo chmod a+x /usr/local/aerofs/tools/*.sh

PYTHON_ROOT=/usr/local/aerofs/python
for module in $(ls $PYTHON_ROOT 2>/dev/null)
do
    cd $PYTHON_ROOT/$module
    sudo python setup.py install
done

# Install python and pyramid
sudo easy_install python pyramid protobuf
