#!/bin/bash
java \
    -XX:+AggressiveOpts \
    -XX:+UseFastAccessorMethods \
    -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/aerofs \
    -Dlogback.configurationFile=./logback.xml \
    -jar cmd-server.jar cmd-server.yml
