#!/bin/bash

NUM_BASE_ARGS=1
NUM_TAG_COMMAND_ARGS=2
E_BADARGS=1
E_BADTAGARGS=2
BASEDIR=`pwd`

if [ $# -lt $NUM_BASE_ARGS ]
then
    echo "usage: `basename $0` [help|tag|untag]"
    exit $E_BADARGS
fi

tag() {
    TAG_NAME=$1 # $1 is the first argument passed to this function

    echo "--------------------------------------------------------------------------------"
    echo "tag:$AD w/ $TAG_NAME"
    git tag -a -m "$TAG_NAME" $TAG_NAME
    git push --tags
}

untag() {
    TAG_NAME=$1 # $1 is the first argument passed to this function

    echo "--------------------------------------------------------------------------------"
    echo "untag:$AD w/ $TAG_NAME"
    git tag -d $TAG_NAME
    git push origin :refs/tags/$TAG_NAME
}

# keep this below function definitions so that bash can find and execute the commands

COMMAND=$1

case "$COMMAND" in
    "tag" | "untag" )
        # it's simpler to put the argument checks here (can't see $@, $# etc. inside a function)
        if [ $# -ne $NUM_TAG_COMMAND_ARGS ]
        then
            echo "usage: `basename $0` $1 [tag name]"
            exit $E_BADTAGARGS
        fi

        # runs either tag or untag function with the tag name
        $1 $2
        ;;
    "help" | "--h" )
        echo "tag:      | $0 tag [tag_name]   | tag all subprojects and the aerofs project with [tag_name] and push tags and aerofs update-commit to origin/master"
        echo "untag:    | $0 untag [tag_name] | untag [tag_name] from all subprojects and the aerofs project and remove from origin/master"
        echo "help:     | $0 help             | print this help message"
        ;;
esac
