#!/usr/bin/env python
from aerofs_licensing.crypto import sign, verify
from aerofs_licensing import license_file
import sys

if __name__ == "__main__":
    action = sys.argv[1]
    input_filename = sys.argv[2]
    output_filename = sys.argv[3]
    if action == "sign":
        with open(input_filename) as f:
            with open(output_filename, "wb") as g:
                sigs = sign(f, g)
                print sigs
    elif action == "verify":
        with open(input_filename) as f:
            with open(output_filename, "wb") as g:
                sigs = verify(f, g)
                print sigs
    elif action == "extract":
        print "extracting {} to {}".format(input_filename, output_filename)
        with open(input_filename) as f:
            files = license_file.verify_and_extract(f, output_filename)
            print files
    elif action == "signcsv":
        # for each line in input_filename:
        #     generate new license
        with open(input_filename) as f:
            pass
    elif action == "test":
        with open(input_filename) as f:
            d  = license_file.verify_and_load(f)
            print d
    else:
        print "Sorry, I don't know that action."

