#!/bin/bash

# first stop zephyr if it is running
service zephyr stop || true

# create the required user, if it hasn't been created yet.
info=$(id zephyr 2>/dev/null)
if [ "$info" = "" ]
then
    useradd -m -s /bin/bash zephyr
fi
