name 'aerofs-ca'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'Module for the ca server'
description 'Set up a certificate authority server'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
