#!/bin/bash

DEAD_EJABBERD_RC=3
EJABBERDCTL_BIN=/usr/sbin/ejabberdctl

$EJABBERDCTL_BIN status
if [ $? -eq $DEAD_EJABBERD_RC ]
then
        # ejabberd is not up

        # this is a hack, and this is the one that's preventing me from running
        # a cron for the staging ejabberd
        echo "killing epmd"
        EPMD_PID=`pgrep epmd`
        kill -9 $EPMD_PID || echo "epmd is dead"

        echo "killing beam"
        BEAM_PID=`pgrep beam`
        kill -9 $BEAM_PID || echo "beam is dead"

        echo "restarting ejabberd"
        service ejabberd start
fi
