name    'aerofs-motd'
version '0.0.1'
source 'UNKNOWN'
author 'Peter Hamilton <peter@aerofs.com>'
license 'Apache License, Version 2.0'
summary 'motd for aerofs servers'
description 'motd for aerofs servers'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
