FROM alpine:3.3

MAINTAINER AeroFS "support@aerofs.com"

RUN apk --update add \
        bash \
        curl \
        dpkg \
        fakeroot \
        p7zip \
        py-flask \
        py-pip \
        py-psutil \
        py-requests \
        python \
        tar \
        util-linux \
        xz \
        zip && \
    rm -rf /var/cache/apk/*
