#!/bin/bash -e

if [ $# -ne 1 ]
then
    echo "usage: $0 <module>"
    exit 1
fi

module=$1
cd $(dirname $0)/../..

# --------------------------------------------------------------------
# Install JMeter
# --------------------------------------------------------------------

list=$(brew list | grep jmeter)
if [ -z "$list" ]
then
    echo "Installing JMeter."
    brew install jmeter
fi

# --------------------------------------------------------------------
# Install graphing plugin
# --------------------------------------------------------------------

PLUGINJAR="jmeter-plugins-0.5.3.jar"
PLUGINSRC="resource/client/common/lib.test"
LIBEXT="/usr/local/Cellar/jmeter/2.7/libexec/lib/ext"

if [ ! -f "$LIBEXT/$PLUGINJAR" ]
then
    echo "Copy jmeter plugins to jmeter lib/ext directory."
    cp $PLUGINSRC/$PLUGINJAR.gz $LIBEXT
    gunzip $LIBEXT/$PLUGINJAR.gz
fi

# --------------------------------------------------------------------
# Install our jars.
# --------------------------------------------------------------------

for jar in $(ls out.ant/jmeter/${module}/*.jar)
do
    basejar=$(basename $jar)

    if [ ! -f "$LIBEXT/$basejar" ]
    then
        echo "Create soft link for $basejar"
        ln -s $(pwd)/$jar $LIBEXT
    fi
done
