#!/bin/bash -e

if [ $# -ne 1 ]
then
    echo "usage: $0 <module>"
    exit 1
fi

module=$1
cd $(dirname $0)/../..

echo "Starting java GUI for $module..."
jmeter -t src/$module/resources/$module.jmx &
