/*
 * Copyright (c) Air Computing Inc., 2012.
 */

package com.aerofs.daemon.core.phy.block;

import com.aerofs.lib.ContentHash;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * Backend performing the actual block storage
 *
 * The storage backend implement a very basic key,value store. Values are arbitrary blocks of binary
 * data and keys are some unspecified cryptographic hash of the values (most likely SHA-256 but not
 * guaranteed by this interface).
 *
 * Remote backends should be proxied through a cache to reduce latency
 */
public interface IBlockStorageBackend
{
    void init_() throws IOException;

    /**
     * Read a block from the storage backend
     */
    InputStream getBlock(ContentHash key) throws IOException;

    /**
     * Base class for blocks to allow metadata generated by encoders to be passed to putBlock
     */
    static interface IBlockMetadata
    {
        ContentHash getKey();
        long getDecodedLength();

        Object getEncoderData();
        void setEncoderData(Object d);
    }

    /**
     * Used to perform any backend-specific encoding and/or checksum computation on which the actual
     * storage operation depends.
     */
    OutputStream wrapForEncoding(OutputStream out, IBlockMetadata meta) throws IOException;

    /**
     * Write a block to the storage backend
     *
     * NOTE: the input stream is guaranteed to be repeatable, i.e calling reset() will bring the
     * position back to the start of the block without any loss.
     */
    void putBlock(IBlockMetadata meta, InputStream input) throws IOException;
}
