/*
 * Copyright (c) Air Computing Inc., 2012.
 */

package com.aerofs.sp.server.lib.cert;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.cert.CertificateException;
import java.util.Date;

/**
 * This class encapsulates certificates that have been generated by the AeroFS certificate
 * authority.
 */
public class Certificate
{
    // The raw certificate bytes.
    private byte[] _certificateBytes;

    // The certificate in x509 format.
    private X509Certificate _x509;

    public Certificate(byte[] certificateBytes)
            throws CertificateException
    {
        this._certificateBytes = certificateBytes;
        InputStream in = new ByteArrayInputStream(_certificateBytes);

        this._x509 = (X509Certificate) CertificateFactory.getInstance("X.509")
                .generateCertificate(in);
    }

    /**
     * @return the string representation of the certificate.
     */
    public String toString()
    {
        return new String(_certificateBytes);
    }

    /**
     * @return the serial number of the certificate as generated by the certificate authority.
     */
    public long getSerial()
    {
        return _x509.getSerialNumber().longValue();
    }

    /**
     * @return the expire timestamp of this certificate.
     */
    public Date getExpiry()
    {
        return _x509.getNotAfter();
    }
}