name    'aerofs-puppet'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'module for managing puppet'
description 'module for managing puppet in both master and agent configurations'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
