hosts: []
access: 
  c2s: 
    blocked: deny
    all: allow
  max_user_sessions: 
    all: 10
  muc: 
    all: allow
  register: 
    all: allow
acl: 
  local: 
    user_regexp: 
      - ""
auth_method: external
extauth_program: "/etc/ejabberd/auth_all"
language: "en"
listen: 
  - 
    port: 5222
    module: ejabberd_c2s
    certfile: "/etc/ejabberd/ejabberd.pem"
    starttls: true
    max_stanza_size: 65536
    access: c2s
loglevel: 4
max_fsm_queue: 1000
modules:
  mod_sic: [] # XEP-0279 Server IP Check (allows client to ask the server for their own IP address)
  mod_vcard: [] # XEP-0054 vCard support (for sending presence locations as metadata)
  mod_ping: []
  mod_disco: []
  mod_muc:
    host: "c.@HOST@"
    access: muc
    access_create: muc
    access_persistent: muc
    max_user_conferences: 50000
    default_room_options: 
      persistent: true
      public: true
      public_list: true
      logging: false
odbc_database: "ejabberd"
odbc_password: "password"
odbc_port: 3306
odbc_server: "mysql.service"
odbc_type: mysql
odbc_username: "ejabberd"
registration_timeout: infinity
