#cloud-config
coreos:
  update:
    reboot-strategy: off
  units:
    - name: "docker.service"
      drop-ins:
        - name: "50-extra-options.conf"
          content: |
            [Service]
            # 172.17.42.1 is for rawdns only
            Environment='DOCKER_OPTS=--dns="172.17.42.1" --dns="172.16.0.83"'

write_files:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      # Point to vpn.arrowfs.org
      DNS=172.16.0.83
