/*
 * Copyright (c) Air Computing Inc., 2012.
 */

package com.aerofs.labeling;

/**
 * L stands for "Labeling". We use a single letter as class name for convenience, as many classes
 * refer to it.
 *
 * How labeling is implemented:
 * ----
 *
 * The GeneratedLabeling class defines the labeling used by AeroFS. This class is generated by bash
 * script tools/build/generate_labeling (also see the "labeling" target in build.xml). This script
 * takes one of the classes in com.aerofs.labeling.impl specified by the user, and uses it as the
 * content of GeneratedLabeling.
 *
 * When building aerofs.jar, the build system removes the entire impl package to avoid revealing
 * unused labeling information.
 */
public class L
{
    private final static ILabeling s_l = new GeneratedLabeling();

    // these constants provide easy access to commonly used values
    public final static String PRODUCT = s_l.product();

    public static ILabeling get()
    {
        return s_l;
    }
}
