#!/bin/bash

# This script creates the approot directory and populates it
# with the files needed for a staging AeroFS

set -e

if [ x"$1" == x ]; then
    echo "usage: $0 <approot> <resource/client>"
    echo "    <approot>: the approot folder path which doesn't need to pre-exist,"
    echo "    <resource/client> is the resource/client folder path which must exist."
    exit 1
fi
APPROOT="$1"
ASIS="$2"
VERSION_FILE=version

PPWD=`dirname $0`
OS=`"$PPWD"/os`

# Copy files to approot
mkdir -p "$APPROOT"
rm -rf "$APPROOT"/Growl.framework # Symlinks prevent cp from overwriting the files
cp -R "$ASIS"/common/* "$APPROOT"/
cp -R "$ASIS"/s3/lib/* "$APPROOT"/lib/
cp -R "$ASIS"/$OS/* "$APPROOT"/

# Set-up a staging environment
touch "$APPROOT"/stg
echo "100.0.0" > "$APPROOT"/$VERSION_FILE
rm "$APPROOT"/cacert-prod.pem
mv "$APPROOT"/cacert-staging.pem "$APPROOT"/cacert.pem

# Add the run script.
cp "$PPWD/os" "$PPWD/run" "$APPROOT"/

