#!/bin/bash

# usage: run <rtroot> <app> [args]

if [ x`uname -s | grep -i 'cygwin\|mingw'` != x ]; then
    S=';'
else
    S=':'
fi

# derive PPWD
PPWD=`dirname $0`

# convert '/cygdrive/X/' to 'X:/'. otherwise JVM wouldn't recognize the path
PPWD=`echo $PPWD | sed -e 's|/cygdrive/\([a-zA-Z]\)/|\1:/|'`

S3ROOT="$PPWD/../java/aerofs.s3"

OS=`"$PPWD"/os`

if [ $OS == osx ]; then
    VMARGS="$VMARGS -XstartOnFirstThread"
    export DYLD_LIBRARY_PATH=$PPWD:$DYLD_LIBRARY_PATH
elif [ x`echo $OS | grep linux` != x ]; then
    export LD_LIBRARY_PATH=$PPWD:$LD_LIBRARY_PATH
fi

CP="$PPWD/bin"
for i in "$PPWD"/lib/*.jar "$S3ROOT"/lib/*.jar; do
    CP="$CP$S$i"
done

VMARGS_DBG="$VMARGS -Xmx64m -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
VMARGS_PROD="$VMARGS -Xmx64m -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError"
#VMARGS="$VMARGS -agentlib:hprof=cpu=samples,depth=16"
#VMARGS="$VMARGS -agentlib:hprof=heap=sites,depth=16"

# set DEBUG to "gdb --args" to run in debugger
$DEBUG java $VMARGS_PROD -Djava.library.path="$PPWD" -ea -cp "$CP" com.aerofs.Main "$@"
