- name: "Ensure /etc/hosts is present"
  copy: dest=/etc/hosts force=no content="127.0.0.1 localhost"
  become: true

- name: "Write appliance IP for share.syncfs.com to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*share\.syncfs\.com$'
    line: "{{ appliance[0] }} share.syncfs.com"
    state: present
  become: true

- name: Update apt cache
  apt: update_cache=yes
  become: true

- name: Install requirements
  package: name={{ item }} state=present
  with_items:
    - jq
    - python-pip
  become: true

- name: Install docopt
  pip: name=docopt state=present
  become: true
