#!/bin/bash
#
# This script tests the Dryad server configuration by making a POST call to
# its REST API.
#
# Note that it will attempt to delete the logs uploaded from the previous
# tests.
#
set -e

usage()
{
    echo "usage: $(basename $0)"
    exit 1
}

if [ $# -ne 0 ] ; then
    usage
fi

# Delete the logs uploaded by previous tests
rm -rf /data/0/00000000000000000000000000000000

TEMP=$(mktemp)
echo 'yes' > "$TEMP"

RESULT=$(curl -i -X POST \
    --insecure \
    --header "Content-Type:application/octet-stream" \
    --data-binary "$TEMP" \
    --silent \
    --output /dev/null \
    --write-out "%{http_code}" \
    https://localhost/v1.0/client/0/00000000000000000000000000000000/test@example.com/00000000000000000000000000000000/logs)

if [ "$RESULT" -ge 200 ] && [ "$RESULT" -lt 300 ] ; then
    echo "Success!"
else
    echo "Failed: $RESULT"
fi

rm "$TEMP"
