#!/bin/bash
#
# This script tests the Dryad server configuration by making a PUT call to
# its REST API.
#
# Note that it will attempt to delete the logs uploaded from the previous
# tests.
#
set -e

usage()
{
    echo "usage: $(basename $0)"
    exit 1
}

if [ $# -ne 0 ] ; then
    usage
fi

TEMP=$(mktemp)
echo 'yes' > "$TEMP"

RESULT=$(curl -i -X PUT \
    --insecure \
    --header "Content-Type:application/octet-stream" \
    --data-binary "$TEMP" \
    --silent \
    --output /dev/null \
    --write-out "%{http_code}" \
    https://localhost/v1.0/defects/00000000000000000000000000000000/client/test@example.com/00000000000000000000000000000000)

if [ "$RESULT" -ge 200 ] && [ "$RESULT" -lt 300 ] ; then
    echo "Success!"
else
    echo "Failed: $RESULT"
fi

rm "$TEMP"
