#!/bin/bash
#
# Sets up the Dryad server using the default configuration.
#
set -e

usage()
{
    echo "usage: $(basename $0)"
    exit 1
}

if [ $# -ne 0 ] ; then
    usage
    exit
fi

source $(dirname $0)/aerofs-dryad-common
checkPrivilege

# Install self-signed certs
$(dirname $0)/generate-and-install-cert custom "$NGINX_DIR"/certs

# Provision Nginx with custom sites
$(dirname $0)/aerofs-dryad-nginx-setup $(dirname $0)/aerofs-dryad-nginx-site $(dirname $0)/aerofs-dryad-nginx-backend

# create the data directory
DATA_DIR=/data
mkdir -p "$DATA_DIR"
chown dryad:dryad "$DATA_DIR"

# link to upstart job and restart the services
ln -snf /lib/init/upstart-job /etc/init.d/dryad
update-rc.d dryad defaults
service dryad restart
service nginx restart

# sleep 1 to ensure the services have restarted before we start testing
sleep 1

# test
echo
echo "> Testing Dryad configuration..."
echo
$(dirname $0)/aerofs-dryad-test
