#!/bin/bash
#
# Sets up the Dryad server using the default configuration.
#
set -e

usage()
{
    echo "usage: $(basename $0)"
    exit 1
}

if [ $# -ne 0 ] ; then
    usage
    exit
fi

OPT=$(dirname $0)

source "$OPT"/aerofs-dryad-common
checkPrivilege

# Install self-signed certs
"$OPT"/generate-and-install-cert custom "$NGINX_DIR"/certs

# Provision Nginx with custom sites
"$OPT"/aerofs-dryad-nginx-setup "$OPT"/aerofs-dryad-nginx-site "$OPT"/aerofs-dryad-nginx-backend

# create the data directory
DATA=/data
if [ ! -d "$DATA" ]
then
    mkdir -p "$DATA"
    chown dryad:dryad "$DATA"
fi

# link to upstart job and restart the services
ln -snf /lib/init/upstart-job /etc/init.d/dryad
update-rc.d dryad defaults
service dryad restart
service nginx restart

# sleep 1 to ensure the services have restarted before we start testing
sleep 1

# test
echo
echo "> Testing Dryad configuration..."
echo
"$OPT"/aerofs-dryad-test
