#!/bin/bash
# first stop service if it is running
service charlie stop || true

# create the required user, if it hasn't been created yet.
info=$(id charlie 2>/dev/null)
if [ "$info" = "" ]
then
    useradd --system --create-home --user-group --shell /bin/bash charlie
fi
