#!/bin/bash
set -e -u

PUPPET_MASTER=puppet.arrowfs.org

# Get the directory this script is in no matter where it's called from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Get the absolute path
AEROFS_GIT_ROOT="$( cd $SCRIPT_DIR/../..; pwd )"
PUPPET_ROOT=${AEROFS_GIT_ROOT}/puppetmaster

echo ">>> Creating directory to rsync puppet content..."
ssh ${PUPPET_MASTER} "mkdir -p /tmp/puppet/$USER"

echo ">>> Rsync content from local to temporary directory on server..."
rsync --exclude ".swp" --delete -avz ${PUPPET_ROOT} ${PUPPET_MASTER}:/tmp/puppet/$USER

echo ">>> Rsync content from temporary directory on server to master location..."
ssh ${PUPPET_MASTER} "rsync -rl --delete /tmp/puppet/$USER/puppetmaster/* /etc/puppet"

echo ">>> Success! Puppet master updated."
exit 0
