#!/bin/bash -e

set -e -u

if [ $# -ne 2 ]; then
    echo "usage: $0 <puppetmaster_ip> <puppetagent_ip>"
    exit 1
fi

PUPPET_MASTER=${1:-}
if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppet agent server address is required"
    exit 2
fi

PUPPET_AGENT=${2:-}
if [ x"$PUPPET_AGENT" == x ]; then
    echo "puppet agent server address is required"
    exit 3
fi

USER=root
# Get the directory this script is in no matter where it's called from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the absolute path
AEROFS_GIT_ROOT="$(cd $SCRIPT_DIR/../..; pwd)"
PUPPET_ROOT=${AEROFS_GIT_ROOT}/puppetmaster/
SSH_KEY=${SCRIPT_DIR}/id_rsa
SSH_COMMAND="ssh -l ${USER} -i ${SSH_KEY}"
HOSTNAME=$($SSH_COMMAND $PUPPET_MASTER -C "hostname")

echo "Configuring puppet agent vm: ${PUPPET_AGENT}"
echo "Installing puppet"
$SSH_COMMAND ${PUPPET_AGENT} -C "apt-get update"
$SSH_COMMAND ${PUPPET_AGENT} -C "apt-get install --yes puppet"
echo "Adding entry in hosts file:  ${PUPPET_MASTER}     ${HOSTNAME}"
$SSH_COMMAND ${PUPPET_AGENT} -C "echo ${PUPPET_MASTER}  ${HOSTNAME} >> /etc/hosts"

echo "Done!"
