#!/bin/bash

set -e -u

if [ $# -ne 2 ]; then
    echo "usage: $0 puppetmaster puppetagent"
    echo "puppetmaster: the address of the puppetmaster server"
    echo "puppetagent: the address of the puppetagent server"
    echo
    echo "example: $0 192.168.1.83 192.168.1.86"
    exit 2
fi

PUPPET_MASTER=${1:-}
if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppet agent server address is required"
    exit 3
fi

PUPPET_AGENT=${2:-}
if [ x"$PUPPET_AGENT" == x ]; then
    echo "puppet agent server address is required"
    exit 3
fi

USER=root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # get the directory this script is in no matter where it's called from
AEROFS_GIT_ROOT="$(cd $SCRIPT_DIR/../..; pwd)" # get the absolute path
PUPPET_ROOT=${AEROFS_GIT_ROOT}/puppetmaster/
SSH_KEY=${SCRIPT_DIR}/id_rsa
SSH_COMMAND="ssh -l ${USER} -i ${SSH_KEY}"
HOSTNAME=$($SSH_COMMAND $PUPPET_MASTER -C "hostname")

echo "Configuring puppet agent vm: ${PUPPET_AGENT}"
echo "Installing puppet"
$SSH_COMMAND ${PUPPET_AGENT} -C "apt-get install puppet"
echo "Adding entry in hosts file:  ${PUPPET_MASTER}     ${HOSTNAME}"
$SSH_COMMAND ${PUPPET_AGENT} -C "echo ${PUPPET_MASTER}  ${HOSTNAME} >> /etc/hosts"

echo "Done!"
