#!/bin/bash

set -e -u

if [ $# -gt 1 ]; then
    echo "usage: $0 [puppetmaster]"
    echo "[puppetmaster]: the address of the puppetmaster server"
    echo
    echo "example: $0 puppet.arrowfs.org"
    exit 2
fi

PUPPET_MASTER=${1:-}
if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppetmaster server address is required"
    exit 3
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # get the directory this script is in no matter where it's called from
AEROFS_GIT_ROOT="$( cd $SCRIPT_DIR/../..; pwd )" # get the absolute path
PUPPET_ROOT=${AEROFS_GIT_ROOT}/puppetmaster/

# rsync - recursuve/follow symlinks - use kssh - exclude ./local (used for vm testing only) - exclude .swp
rsync -v -rl -e "kssh" --exclude "local" --exclude ".swp" ${PUPPET_ROOT} ${PUPPET_MASTER}:/etc/puppet

echo "Success"
exit 0
