#!/bin/bash

set -e -u

usage()
{
    echo "usage: $0 <puppetmaster>"
    echo "example: $0 puppet.arrowfs.org"
    exit $1
}

if [ $# -ne 1 ]; then
    usage 2
fi

PUPPET_MASTER=${1:-}

if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppetmaster server address is required."
    usage 3
fi

# Get the directory this script is in no matter where it's called from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Get the absolute path
AEROFS_GIT_ROOT="$( cd $SCRIPT_DIR/../..; pwd )"
PUPPET_ROOT=${AEROFS_GIT_ROOT}/puppetmaster

# rsync - recursuve/follow symlinks - use kssh - exclude ./local (used for vm testing only).
rsync -v -rl --delete -e "ssh" --exclude "local" --exclude ".swp" ${PUPPET_ROOT} ${PUPPET_MASTER}:/etc/puppet

echo "Success"
exit 0
