#!/bin/bash

set -e -u

if [ $# -lt 2 ]; then
    echo "Usage: $0 <puppetmaster> <puppet agent> [retry attempts]"
    echo ""
    echo "<puppetmaster>: the address of the puppetmaster server"
    echo "<puppet agent>: the hostname of the puppet agent"
    echo "[retry attempts]: the number of times to retry (in the event the machine is already being kicked)"
    echo
    echo "Example: $0 puppet.arrowfs.org z.arrowfs.org"
    exit 2
fi

PUPPET_MASTER=${1:-}
PUPPET_AGENT=${2:-}
TTL=${3:-}

if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppetmaster server address is required"
    exit 3
fi

if [ x"$TTL" == x ]; then
    TTL=10
fi

ssh ${PUPPET_MASTER} -C "kick ${PUPPET_AGENT} ${TTL}"

exit 0
