#!/bin/bash

set -e -u

if [ $# -gt 2 ]; then
    echo "usage: $0 [puppetmaster] [puppet agent]"
    echo "[puppetmaster]: the address of the puppetmaster server"
    echo "[puppet agent]: the hostname of the puppet agent"
    echo
    echo "example: $0 puppet.arrowfs.org z.arrowfs.org"
    exit 2
fi

PUPPET_MASTER=${1:-}
if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppetmaster server address is required"
    exit 3
fi

PUPPET_AGENT=${2:-}
if [ x"$PUPPET_AGENT" == x ]; then
    echo "puppet agent hostname is required"
    exit 3
fi

kssh ${PUPPET_MASTER} -C "puppet kick ${PUPPET_AGENT}"

exit 0
