#!/bin/bash

set -e -u

if [ $# -ne 1 ]; then
    echo "usage: $0 [puppetmaster]"
    echo "[puppetmaster]: the address of the puppetmaster server"
    echo
    echo "example: $0 puppet.arrowfs.org"
    exit 2
fi

PUPPET_MASTER=${1:-}
if [ x"$PUPPET_MASTER" == x ]; then
    echo "puppetmaster server address is required"
    exit 3
fi

KICKLIST="sp.aerofs.com sv.aerofs.com verkehr.aerofs.com webadmin.aerofs.com x.aerofs.com"

ssh ${PUPPET_MASTER} -C "echo `date` >> /var/log/aerofs/kickall.log"
ssh ${PUPPET_MASTER} -C "set -o pipefail; puppet kick --foreground --parallel 2 --debug $KICKLIST | tee -a /var/log/aerofs/kickall.log"
