#!/usr/bin/env python
import subprocess

MAX_DAYS_TO_KEEP = 21
# At 10 days' worth we regularly use up 100% of SV's disk. Shall we try 6?
# The effect of keeping this value too high is that we lose logs anyway,
# the zero-length zip files aren't helping anyone.
MIN_DAYS_TO_KEEP = 6
# If the disk space usage is above this threshold, the script will free up
# more disk space. This is set to 90 to be consistent with the pagerduty
# probe, which will trigger if the disk usage is above 90%.
FREE_SPACE_THRESHOLD = 90

def get_percent_free():
    try:
        output = subprocess.check_output("df -h | grep /data | awk '{ print $5 }'", shell=True)
        percent = int(output.strip().strip("%"))
        print "/data is {0}% in use".format(percent)
        return percent
    except subprocess.CalledProcessError as e:
        print e.output
        raise e

def clean_defects(days_to_keep):
    print "removing everything older than {0} days old".format(days_to_keep)
    subprocess.check_output('find /var/svlogs_prod/defect/ -mtime +{0} -iname log.defect\* | xargs -r rm'.format(days_to_keep), shell=True)

def main():
    """
    We always clean things over MAX_DAYS_TO_KEEP days old. We always keep things less than MIN_DAYS_TO_KEEP days
    old. For everything in between, we keep as much as we can while maintaining 5 % free
    """
    days_to_keep = MAX_DAYS_TO_KEEP
    clean_defects(days_to_keep)
    days_to_keep = days_to_keep - 1
    while get_percent_free() > FREE_SPACE_THRESHOLD and days_to_keep > MIN_DAYS_TO_KEEP:
        clean_defects(days_to_keep)
        days_to_keep = days_to_keep - 1

if __name__ == "__main__":
    exit(main())
