#!/bin/bash

# Disable pip installs. Make them no-ops. This will allow us to install
# aerofs-web without an internet connection.

for executable in \
    /opt/web/pythonenv/bin/pip \
    /usr/local/bin/virtualenv \
    /usr/bin/pip
do
    echo > $executable
done
