# recognize third party deps in vendor/ dir
# must use go v1.5 or greater
export GO15VENDOREXPERIMENT = 1

include ../../Makefile.base

IMAGE_NAME = aeropush/button
PACKAGE_NAME = aerofs.com/button
TAG = alpha

GOCKERIZE_CTX = ../..
