name    'aerofs-hipchat'
version '0.0.1'
source 'UNKNOWN'
author 'Peter Hamilton <peter@aerofs.com>'
license 'Apache License, Version 2.0'
summary 'send messages to hipchat'
description 'send messages to a hipchat room for various things"
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
