/*
 * Copyright (c) Air Computing Inc., 2012.
 */

package com.aerofs.labeling;

import java.util.Properties;

/**
 * L stands for "Labeling". We use a single letter as class name for convenience, as many classes
 * refer to it.
 *
 * How labeling is implemented:
 * ----
 *
 * The GeneratedLabeling class defines the labeling used by AeroFS. This class is generated by bash
 * script tools/build/generate_labeling (also see the "labeling" target in build.xml). This script
 * takes one of the classes in com.aerofs.labeling.impl specified by the user, and uses it as the
 * content of GeneratedLabeling.
 *
 * When building aerofs.jar, the build system removes the entire impl package to avoid revealing
 * unused labeling information.
 */
public class L
{
    private static ILabeling get()
    {
        return LazyHolder.s_l;
    }

    public static String brand() {
        return get().brand();
    }

    public static boolean isMultiuser() {
        return get().isMultiuser();
    }

    public static String product() {
        return get().product();
    }

    public static String productSpaceFreeName() {
        return get().productSpaceFreeName();
    }

    public static String productUnixName() {
        return get().productUnixName();
    }

    public static String rootAnchorName() {
        return get().rootAnchorName();
    }

    public static int defaultPortbase() {
        return get().defaultPortbase();
    }

    private static class LazyHolder {
        private static ILabeling s_l = new PropertiesLabeling();
    }

    // TESTING only
    public static void set(Properties p)
    {
        LazyHolder.s_l = new PropertiesLabeling(p);
    }

    // FIXME (AT): remove this method and all references to it when the feature is ready to ship.
    // This flag should be used to shutdown all group sharing features on the desktop client until
    // the entire experience is ready. Developers working on group sharing can toggle this flag to
    // enable all group sharing features for testing purpose.
    public static boolean isGroupSharingReady()
    {
        return false;
    }
}
