USE mysql;
GRANT USAGE ON *.* TO 'test'@'localhost';
DROP USER 'test'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'test'@'localhost' IDENTIFIED BY PASSWORD '*7F7520FA4303867EDD3C94D78C89F789BE25C4EA';
GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost';
FLUSH PRIVILEGES;