# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

BRIDGE_IFACE     = ENV["BRIDGE_IFACE"]
NUMBER_OF_AGENTS = ENV["CLIENT_COUNT"] ? ENV["CLIENT_COUNT"].to_i : 2
BRIDGE_COUNT     = ENV["BRIDGE_COUNT"] ? ENV["BRIDGE_COUNT"].to_i : NUMBER_OF_AGENTS

# If BRIDGE_IFACE is specified, map it to the full interface string.
if BRIDGE_IFACE
    iface = %x( VBoxManage list bridgedifs ).split("\n")
                                            .select{|a| a.start_with?("Name:")}
                                            .map{|a| a.sub(/Name: */, "")}
                                            .select{|a| a[/#{BRIDGE_IFACE}/]}[0]
end

local_key = %x(cut -d ' ' -f 2 ~/.ssh/id_rsa.pub).strip()
agent_key = %x(cut -d ' ' -f 2 ~/agents-build-kit/agents2actors.pub).strip()

# workaround: facter/puppet barfs if the agent key is empty, failing to provision
# event the local key, which is a problem for running syncdet on dev machines as
# the agent pubkey won't be present and failure to provision the local pubkey will
# break syncdet scripts as they expect passwordless ssh
if agent_key.length == 0
  agent_key = local_key
end

name = %x( whoami ).strip()
host_base = "#{name}-vagrant-"

Vagrant.configure("2") do |config|
  NUMBER_OF_AGENTS.times do |index|
      host = host_base + "#{index}"
      config.vm.define host do |config_a|
          config_a.vm.box = "precise64-official"
          config_a.vm.box_url = "http://files.vagrantup.com/precise64.box"
          config_a.vm.network :private_network, ip: "192.168.50.#{index+10}"
          (config_a.vm.network :public_network, :bridge => iface) if BRIDGE_IFACE and index < BRIDGE_COUNT
          config_a.vm.provider "virtualbox" do |vbox|
              vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          end
          config_a.vm.hostname = host
          config_a.vm.provision :puppet do |puppet|
             puppet.manifests_path = "manifests"
             puppet.manifest_file  = "syncdet.pp"
             puppet.options = "--verbose --debug"
             puppet.facter = {
                 "my_ssh_key" => local_key,
                 "agent_vagrant_ssh_key" => agent_key,
             }
          end
      end
  end
end
