#!/bin/bash

# the cut line we use specifies the starting character to the end
# this is equal to the length of the product name plus the dash plus one
# We create a string with the product name plus a dash plus a space and use
# its length in the cut command
PRODUCT="[AEROFS_PRODUCT_UNIX]- "
PROG=`basename $0 | cut -c ${#PRODUCT}-`
if [ x"$PROG" == x ]; then
    PROG=gui
fi

if [ $PROG == gui ]; then
    if [ x"$DISPLAY" == x ]; then
        echo Please use [AEROFS_PRODUCT_UNIX]-cli when running without a graphical environment.
        exit 1
    fi
fi

if [ x"$(file -L /bin/ls | grep 64 )" != x ]; then
    ARCH=64
    PACKAGE_FILENAME=[AEROFS_PRODUCT_UNIX]-x86_64.tgz
    JRE_LIB_ARCH=amd64
else
    ARCH=32
    PACKAGE_FILENAME=[AEROFS_PRODUCT_UNIX]-x86.tgz
    JRE_LIB_ARCH=i386
fi

URL=https://cache.client[DOT_STAGING].aerofs.com/$PACKAGE_FILENAME

DIST="$HOME/.[AEROFS_PRODUCT_UNIX]-bin[DOT_STAGING]"

if [ ! -f "$DIST/aerofs.jar" ]; then
    which ps > /dev/null
    if [ $? != 0 ]; then
        echo Please install the procps package first by typing:
        echo sudo apt-get install procps
        exit 1
    fi
    which uudecode > /dev/null
    if [ $? != 0 ]; then
        echo Please install the sharutils package first by typing:
        echo sudo apt-get install sharutils
        exit 1
    fi
    which java > /dev/null
    if [ $? != 0 ]; then
        echo Please install Java first by typing:
        echo sudo apt-get install default-jre
        exit 1
    fi

    TMP_DIR=$(mktemp -d)
    trap "rm -rf \"$TMP_DIR\"" EXIT

    uudecode -o /dev/stdout $0 | tar xzf - -C $TMP_DIR 2>/dev/null

    if [ $PROG == gui ]; then
        echo "Launching graphical interface... (use [AEROFS_PRODUCT_UNIX]-cli for command-line interface)"
    fi

    TARGET="$TMP_DIR/target"
    mv "$TMP_DIR/libswt$ARCH/libswt"*.so "$TMP_DIR"
    java -cp "$TMP_DIR/s$ARCH.jar":"$TMP_DIR" com.aerofs.downloader.Main $PROG $URL "$TARGET"
    if [ $? != 0 ]; then
        exit 1
    fi

    tar zxf "$TARGET" -C "$TMP_DIR" 2>/dev/null
    if [ ! -d "$TMP_DIR/aerofs" ]; then
      echo Failed during unpacking the AeroFS package.
      exit 1
    fi

    rm -rf "$DIST"
    mv "$TMP_DIR/aerofs" "$DIST"
    rm -rf "$TMP_DIR"

    # setup auto-start
    mkdir -p "$HOME/.config/autostart/"
    rm -f "$HOME/.config/autostart/[AEROFS_PRODUCT_UNIX].desktop"
    ln -s "$DIST/[AEROFS_PRODUCT_UNIX].desktop" "$HOME/.config/autostart/"
else
    # Sanity check - ensure that aerofs libs match 32/64 bitness with userspace
    if [ x"$( file -L "$DIST/aerofsd" | grep 64 )" != x ]; then
        AEROFS_ARCH=64
    else
        AEROFS_ARCH=32
    fi
    if [ x"$AEROFS_ARCH" != x"$ARCH" ]; then
        # Somehow we have the wrong binaries.  Redownload and reinstall.
        TMP_DIR=$( mktemp -d )
        TARGET="$TMP_DIR/retry"
        java -cp $DIST/aerofs.jar com.aerofs.downloader.Main headless $URL "$TARGET"
        rm -rf "$DIST"
        tar zxf "$TARGET" -C "$TMP_DIR" 2>/dev/null
        mv "$TMP_DIR/aerofs" "$DIST"
        cd "$DIST" # Java doesn't like being launched from a deleted folder
        rm -rf "$TMP_DIR"
    fi
fi

JRE_BASE="$(dirname $(dirname $(readlink -f $(which java))))"
# Oracle ships two "java" executables in the JDK package - one in the jre/bin/
# folder, and the other just in the bin/ folder.  This finds the jre even if
# the JDK java binary is the first one on the user's PATH.
if [ -d "$JRE_BASE/jre" ]; then
    JRE_BASE="$JRE_BASE/jre"
fi
JRE_LIB="$JRE_BASE/lib/$JRE_LIB_ARCH"
# for java to load our own native libraries and aerofsd to load jvm libraries
export LD_LIBRARY_PATH="$DIST:$JRE_LIB:$JRE_LIB/server:$LD_LIBRARY_PATH"

if [ $PROG == gui ]; then
    echo "Launching graphical interface in the background... (use [AEROFS_PRODUCT_UNIX]-cli for command-line interface)"
    nohup java -Xmx64m -jar "$DIST/aerofs.jar" DEFAULT gui 2>/dev/null >/dev/null &
else
    java -Xmx64m -jar "$DIST/aerofs.jar" DEFAULT $PROG "$@"
fi

exit 0
