#!/bin/bash
set -e

# TODO: precompile all this; don't rebuild it every time ;_;
cd /opt/stun
source constants

for package in $RE $STUN
do
    wget $URL/$package.tar.gz
    tar xf $package.tar.gz
    cd $package
    make
    make install
done

service restund start || true
