#!/bin/bash
#
# Test if the specified filesystem on the specified remote host exceeds 90% capacity.
#
# exit 1 if the usage exceeds 90%
# exit 2 if the hostname or filesystem is not found
# exit 3 if bad arguments

usage()
{
    echo "usage: $0 <user@host> <port> <filesystem, e.g. rootfs>"
}

if [ $# != 3 ]; then
    usage
    exit 3
fi

LOGIN=$1
PORT=$2
FS=$3
THRESHOLD=90

USED=`ssh -p $PORT $LOGIN df | grep $FS | awk '{print $5}' | sed -e 's/%//'`

if [ x$USED == x ]; then
    # the filesystem is not found
    exit 2
fi

if [ `expr $USED \>= $THRESHOLD` == 1 ]; then
    exit 1
else
    exit 0
fi
