#!/bin/bash
#
# Test if curl of the specified URL returns okay, i.e. HTTP 200.
#
# exit 1 if the URL returns an error, i.e. HTTP 500.

URL='http://enterprise.aerofs.com:8000/hpc_deployments_status'

if [ $# == 1 ]
then
	URL=$1
elif [ $# != 0 ]
then
	echo "usage: $0 [url]" >&2
fi

if [ "$(curl -s -o /dev/null -w "%{http_code}" $URL)" != "200" ]
then
    exit 1
fi
