#!/bin/bash
#
# Test if the number of certain processes on the specified remote host >= the expected number
#
# exit 1 if the process count < the expected count
# exit 2 if the query failed
# exit 3 if bad arguments

usage()
{
    echo "usage: $0 <user@host> <port> <grep keyword for ps> <number of processes expected>"
}

if [ $# != 4 ]; then
    usage
    exit 3
fi

LOGIN=$1
PORT=$2
KEYWORD=$3
EXPECTED=$4

ACTUAL=`kssh -p $PORT $LOGIN "ps -ef | grep $KEYWORD | grep -v grep | wc -l"`

if [ x$ACTUAL == x ]; then
    # query failed
    exit 2
fi

if [ `expr $ACTUAL \< $EXPECTED` == 1 ]; then
    exit 1
else
    exit 0
fi
