#!/bin/bash
#
# Test if wget of the specified URL returns okay, i.e. HTTP 200.
#
# exit 1 if bad arguments
# exit the exit code of 'wget <url>'

usage()
{
    echo "usage: $0 <url>"
}

if [ x"$1" == x ]; then
    usage
    exit 1
fi

wget --timeout=1 --no-cache -q -O /dev/null "$1"
