#!/bin/bash
set -e

if [ $# -ne 1 ]; then
	echo "Create a MySQL database for a service if it doesn't exist,"
	echo "and grant the service's user access to the new database."
    echo "Usage: $0 <service>"
    exit 1
fi

echo Creating MySQL database "$1" if not exists...
cat <<EOF | mysql -h mysql.service
CREATE DATABASE IF NOT EXISTS $1;
GRANT ALL ON $1.* to $1;
EOF
