#!/bin/bash
set -e

if [ $# -ne 1 ]; then
    echo "Get a configuration property's value"
    echo "Usage: $0 <property_name>"
    exit 1
fi

DEPLOYMENT_SECRET="$(cat /data/deployment_secret)"
curl --fail --silent --show-error \
     --header "Authorization: Aero-Service-Shared-Secret container-scripts $DEPLOYMENT_SECRET" \
     config.service:5434/server | grep "^$1=" | sed -e "s/^$1=//" | sed -e 's/\\n/\n/g'
