#!/bin/bash
set -e

if [ $# -ne 1 ]; then
    echo "Get a configuration property's value"
    echo "Usage: $0 <property_name>"
    exit 1
fi

curl -s -S config.service:5434/server | grep "^$1=" | sed -e "s/^$1=//" | sed -e 's/\\n/\n/g'
