# this script is generated by create_db_migrate_script.py
from sqlalchemy import *
from migrate import *


from migrate.changeset import schema
pre_meta = MetaData()
post_meta = MetaData()
unbound_signup = Table('unbound_signup', post_meta,
    Column('id', Integer, primary_key=True, nullable=False),
    Column('signup_code', String(length=45), nullable=False),
    Column('email', Unicode(length=256), nullable=False),
    Column('first_name', String(length=256), nullable=False),
    Column('last_name', String(length=256), nullable=False),
    Column('company_name', String(length=256), nullable=False),
    Column('phone_number', String(length=256)),
    Column('job_title', String(length=256)),
    Column('promo_code', String(length=256)),
)


def upgrade(migrate_engine):
    # Upgrade operations go here. Don't create your own engine; bind
    # migrate_engine to your metadata
    pre_meta.bind = migrate_engine
    post_meta.bind = migrate_engine
    post_meta.tables['unbound_signup'].columns['promo_code'].create()


def downgrade(migrate_engine):
    # Operations to reverse the above upgrade go here.
    pre_meta.bind = migrate_engine
    post_meta.bind = migrate_engine
    post_meta.tables['unbound_signup'].columns['promo_code'].drop()
