# this script is generated by create_db_migrate_script.py
from sqlalchemy import *
from migrate import *


from migrate.changeset import schema
pre_meta = MetaData()
post_meta = MetaData()
hpc_deployment = Table('hpc_deployment', post_meta,
    Column('create_date', DateTime, nullable=False),
    Column('modify_date', DateTime, nullable=False),
    Column('subdomain', String(length=32), primary_key=True, nullable=False),
    Column('customer_id', Integer, nullable=False),
    Column('server_id', Integer, nullable=False),
    Column('expiry_date', DateTime),
    Column('appliance_setup_date', DateTime),
)


def upgrade(migrate_engine):
    # Upgrade operations go here. Don't create your own engine; bind
    # migrate_engine to your metadata
    pre_meta.bind = migrate_engine
    post_meta.bind = migrate_engine
    post_meta.tables['hpc_deployment'].columns['appliance_setup_date'].create()
    post_meta.tables['hpc_deployment'].columns['expiry_date'].create()


def downgrade(migrate_engine):
    # Operations to reverse the above upgrade go here.
    pre_meta.bind = migrate_engine
    post_meta.bind = migrate_engine
    post_meta.tables['hpc_deployment'].columns['appliance_setup_date'].drop()
    post_meta.tables['hpc_deployment'].columns['expiry_date'].drop()
