name    'aerofs-analytics'
version '0.0.1'
source 'UNKNOWN'
author 'Yuri Sagalov <yuri@aerofs.com>'
license 'Apache License, Version 2.0'
summary 'SV analytics'
description 'collect analytics on SV'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
