#!/bin/bash -eu
# This script assumes 2 things:
#   1) s3cmd is set up with access to the aerofs.github bucket
#   2) root has an ssh public key on github.arrowfs.org

rm -rf /mnt/github
mkdir -p /mnt/github

echo "Backing up authorized keys"
ssh admin@github.arrowfs.org -- 'ghe-export-authorized-keys' > /mnt/github/authorized-keys.json
echo "Backing up es indices"
ssh admin@github.arrowfs.org -- 'ghe-export-es-indices' > /mnt/github/es-indices.tar
echo "Backing up mysql"
ssh admin@github.arrowfs.org -- 'ghe-export-mysql' | gzip > /mnt/github/enterprise-mysql-backup.sql.gz
echo "Backing up redis"
ssh admin@github.arrowfs.org -- 'ghe-export-redis' > /mnt/github/backup-redis.rdb
echo "Backing up repositories"
ssh admin@github.arrowfs.org -- 'ghe-export-repositories' > /mnt/github/enterprise-repositories-backup.tar
echo "Backing up settings"
ssh admin@github.arrowfs.org -- 'ghe-export-settings' > /mnt/github/settings.json
echo "Backing up ssh host keys"
ssh admin@github.arrowfs.org -- 'ghe-export-ssh-host-keys' > /mnt/github/host-keys.tar

pushd /mnt/
DATE=$(date -u +%Y%m%d_%H%M%S)UTC
FILENAME=github_${DATE}.tar.bz2
tar cjf /mnt/$FILENAME github
popd

s3cmd put /mnt/$FILENAME s3://aerofs.github/$FILENAME
