containers:
  loader:
    image: aerofs/sa-loader

  storage-agent-setup:
    image: aerofs/storage-agent-setup
    run:
      detach: true
      publish:
        - "443:443"
      #so we don't need to copy all the data on IPU
      volume:
        - /aerofs-storage:/aerofs-storage
      link:
        - loader:loader.service

  storage-agent:
    image: aerofs/storage-agent
    run:
      detach: true
      net: host
      #so we don't need to copy all the data on IPU
      volume:
        - /aerofs-storage:/aerofs-storage

groups:
  default:
    - storage-agent
    - storage-agent-setup
  maintenance:
    - storage-agent-setup

