containers:
  sa-data:
    image: aerofs/sa-data
    run:
      detach: true

  loader:
    image: aerofs/sa-loader

  storage-agent-setup:
    image: aerofs/storage-agent-setup
    run:
      detach: true
      publish:
        - "443:443"
      volumes-from:
        - sa-data
      link:
        - loader:loader.service

  storage-agent:
    image: aerofs/storage-agent
    run:
      detach: true
      net: host
      volumes-from:
        - sa-data

groups:
  default:
    - storage-agent
    - storage-agent-setup
  maintenance:
    - storage-agent-setup

