#!/bin/bash

OPT=/opt/repackaging
SDIST=$OPT/sdist
PYTHONENV=$OPT/pythonenv
rm -rf $PYTHONENV
virtualenv $PYTHONENV
$PYTHONENV/bin/pip install --find-links file://$SDIST                    \
                           --no-index                                    \
                           --log /var/log/aerofs/repackaging.install.log \
                           --requirement $OPT/requirements.txt
