#!/bin/bash

SDIST=/opt/repackaging/sdist
PYTHONENV=/opt/repackaging/pythonenv
rm -rf $PYTHONENV
virtualenv $PYTHONENV
$PYTHONENV/bin/pip install --find-links file://$SDIST                    \
                           --no-index                                    \
                           --log /var/log/aerofs/repackaging.install.log \
                           --requirement $SDIST/requirements.txt
