#!/bin/bash
#
# Script to take a picture of the coder when they push a code review.

changeid=$(git log -1 | grep "Change-Id" | awk -F' ' '{print $2}')

if [ -z "$changeid" ]
then
    echo "No change ID. Is your gerrit commit hook broken?"
    exit 1
fi

file="$(date +%Y%m%d%H%M%S)_${changeid}_$(whoami | tr [a-z] [A-Z]).jpg"

echo "Taking a picture -- smile!"
imagesnap -q -w 3 "$file"

mv $file ~/AeroFS/Air\ Computing\ Review\ Pictures
