#!/bin/bash
#
# Override existing git review alias so that it also takes a picture. Also does
# other required install steps (installs imagesnap and checks that the user has
# access to the aerofs review pictures shared folder.

if [ -z $(brew list | grep imagesnap) ]
then
    brew install imagesnap
fi

if ! [ -d ~/AeroFS/Air\ Computing\ Review\ Pictures ]
then
    echo "ERROR: can't add picture hook."
    echo "Please make sure \"~/AeroFS/Air Computing Review Pictures\" exists."
    exit 0
fi

git config alias.picture '!sh tools/env/git-picture'
echo "Added git alias 'git picture'"

git config alias.review-only '!sh tools/env/git-review'
echo "Added git alias 'git review-only'"

git config alias.review '!sh tools/env/git-review-picture'
echo "Modified git alias 'git review' (added picture hook)"
