#!/bin/bash

# first stop devman if it is running
service devman stop || true

# create the required user, if it hasn't been created yet.
info=$(id devman 2>/dev/null)
if [ "$info" = "" ]
then
    useradd -m -s /bin/bash devman
fi

# create required directories with required permissions
mkdir -p /var/log/aerofs
