# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define :ubuntu do |box|
        box.vm.box = "ubuntu/trusty64"
        box.vm.hostname = "ubuntu"
        box.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.customize ["modifyvm", :id, "--name", "ubuntu"]
            vb.customize ["modifyvm", :id, "--memory", "4096"]
        end
    end
    config.vm.synced_folder "~/Repos", "/mnt/repos"
end
