#!/bin/bash
set -e -u

if [[ $# -ne 3 || "$1x" == "x" || "$2x" == "x" || "$3x" == "x" ]]
then
    echo "usage: $0 [servlet_name] [base_dir] [proj_dir]"
    echo
    echo "example: $0 sv ~/repos/aerofs aerofs.spsv"
    exit 2
fi

SERVLET_NAME="$1"
BASEDIR="$2"
PROJDIR="$3"

PACKAGE_NAME="$SERVLET_NAME"
BUILDROOT="build/$PACKAGE_NAME"

RESOURCES="$BASEDIR"/src/"$PROJDIR"/resources/"$SERVLET_NAME"
INSTALL="$BUILDROOT"/usr/share/aerofs-"$PACKAGE_NAME"/"$SERVLET_NAME"
CONTEXT="$BUILDROOT"/etc/tomcat6/Catalina/localhost
DEBIAN="$BUILDROOT"/DEBIAN

rm -rf "$BUILDROOT"

mkdir -p "$BUILDROOT"
mkdir -p "$INSTALL"
mkdir -p "$CONTEXT"
mkdir -p "$DEBIAN"

# debian files
for F in control
do
    cp -R "$RESOURCES"/$F "$DEBIAN"
done

# package-data files
cp -R "$BASEDIR"/out.ant/artifacts/"$SERVLET_NAME"/exploded/* "$INSTALL"/

CONTEXT_FILENAME="ROOT.xml"
# Since we can't deploy sv to root (due to alpha and staging systems), we deploy
# it at sv_beta
if [ $SERVLET_NAME == "sv" ]
then
    CONTEXT_FILENAME="sv_beta.xml"
fi
