#!/bin/bash
PYTHONENV=/opt/sanity/pythonenv
rm -rf $PYTHONENV
virtualenv $PYTHONENV
$PYTHONENV/bin/pip install --find-links file:///opt/sanity/sdist    \
                           --no-index                               \
                           --log /var/log/aerofs/sanity.install.log \
                           --requirement /opt/sanity/requirements-exact.txt
