name    'aerofs-fwknop-client'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'provides kssh, kscp, fwknop.key and fwknop-client package'
description 'provides tools need to use kssh and kscp'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
