containers:

  hpc-docker-gen:
    image: aerofs/hpc-docker-gen
    run:
      detach: true
      restart: always
      volumes-from:
        - hpc-reverse-proxy
      volume:
        - /var/run/docker.sock:/tmp/docker.sock:ro

  hpc-reverse-proxy:
    image: aerofs/hpc-reverse-proxy
    run:
      detach: true
      restart: always
      publish:
        - "80:80"
        - "443:443"
      volume:
        - /tmp/hpc-reverse-proxy:/etc/nginx/conf.d

  hpc-port-allocator:
    image: aerofs/hpc-port-allocator
    restart: always
    run:
      detach: true
      volume:
        - /var/hpc-port-allocator:/state