package com.aerofs.servlets.lib.analytics;

public enum AnalyticsEvent {
    USER_SIGNUP,
    MOBILE_CLIENT_INSTALL,
    DESKTOP_CLIENT_INSTALL,
    TEAM_SERVER_OFFLINE,
    MOBILE_CLIENT_UNLINK,
    DESKTOP_CLIENT_UNLINK,
    LINK_CREATED,
    FOLDER_INVITATION_SEND,
    FOLDER_INVITATION_ACCEPT,
    USER_INVITATION_SEND,
    USER_INVITATION_ACCEPT,
    BYTES_SYNCED,
    USER_DELETE,
    SHARED_FOLDER_CREATE;
}
