name    'aerofs-common'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'Common infrastructure'
description 'Common infrastructure - stuff that normally goes in site.pp"
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
