#!/bin/bash
chmod -R 644 /opt/config/properties

PYTHONENV=/opt/config/pythonenv
rm -rf $PYTHONENV
virtualenv $PYTHONENV
$PYTHONENV/bin/pip install --find-links file:///opt/config/sdist    \
                           --no-index                               \
                           --log /var/log/aerofs/config.install.log \
                           --requirement /opt/config/requirements-exact.txt
