#!/bin/bash
if [ $1 == purge ]
then
    rm -rf /opt/bunker/build
    rm -rf /opt/bunker/dist
    rm -rf /opt/bunker/extra
    rm -rf /opt/bunker/pythonenv
    rm -rf /opt/bunker/web
    rm -rf /opt/bunker/web.egg-info
fi
