#!/bin/bash
set -e

chown www-data:www-data /var/log/bunker -R

# A folder where the bunker can write some state.
# In particular, a randomly-generated private csrf_token.
chown www-data:www-data /opt/bunker/state -R

PYHOME=/opt/bunker/pythonenv
PYTHON=$PYHOME/bin/python

# Produce clean virtualenv from scratch
pushd /opt/bunker
rm -rf $PYHOME
mkdir -p $PYHOME
virtualenv $PYHOME

$PYHOME/bin/pip install --find-links file:///opt/bunker/sdist    \
                        --no-index                               \
                        --log /var/log/bunker/bunker.install.log \
                        --requirement /opt/bunker/requirements-exact.txt

# For some reason this value gets set to /root/.python-eggs which is
# not writable by www-data. Explicitly setting it fixes the problem.
export PYTHON_EGG_CACHE=/var/www/.python-eggs

# Return to initial starting folder
popd
