#!/bin/bash
set -e

chown www-data:www-data /var/log/web -R

PYHOME=/opt/web/pythonenv
PYTHON=$PYHOME/bin/python

# Enter temp directory to build python packages
TMPDIR=/tmp/aerofs_web_build
mkdir $TMPDIR
pushd $TMPDIR

# Produce clean virtualenv from scratch
rm -rf $PYHOME
mkdir -p $PYHOME
virtualenv $PYHOME

cd /opt/web
$PYHOME/bin/pip install --find-links file:///opt/web/sdist      \
                        --no-index                              \
                        --log /var/log/web/web.install.log   \
                        --requirement /opt/web/requirements.txt
$PYTHON setup.py install

# Install aerofs.python-lib
# cd to directory first because setuptools can't find setup.py otherwise
pushd /opt/web/extra/python-lib
$PYTHON setup.py install
popd

# For some reason this value gets set to /root/.python-eggs which is
# not writable by www-data. Explicitly setting it fixes the problem.
export PYTHON_EGG_CACHE=/var/www/.python-eggs

# Back to original directory, clean up temp directory
popd
rm -r $TMPDIR
