#!/bin/bash
set -e

chown www-data:www-data /var/log/web -R

PYHOME=/opt/web/pythonenv
PYTHON=$PYHOME/bin/python

# Produce clean virtualenv from scratch
pushd /opt/web
rm -rf $PYHOME
mkdir -p $PYHOME
virtualenv $PYHOME

$PYHOME/bin/pip install --find-links file:///opt/web/sdist      \
                        --no-index                              \
                        --log /var/log/web/web.install.log   \
                        --requirement /opt/web/requirements-exact.txt

# For some reason this value gets set to /root/.python-eggs which is
# not writable by www-data. Explicitly setting it fixes the problem.
export PYTHON_EGG_CACHE=/var/www/.python-eggs

# Return to initial starting folder
popd
