#!/bin/bash
set -e

if [ $# -ne 1 ]; then
    echo "Copy AeroFS CA's root cert to \$1/cacert.pem."
    echo "It requires the container to depend on CA's container."
    echo "Usage: $0 <path>"
    exit 1
fi

echo "Downloading cacert.pem..."
curl --fail -o "$1"/cacert.pem http://ca.service:9002/prod/cacert.pem
