#!/bin/bash
set -e

curl --fail -o /tmp/cacert.pem http://ca.service:9002/prod/cacert.pem

# PREDOCKER it should call CA's API rather than accessing CA's data volume.
echo "Importing cacert.pem to Java..."
keytool \
    -import \
    -alias pd-$(date +%s) \
    -file /tmp/cacert.pem \
    -keystore /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts \
    -storepass "changeit" \
    -noprompt
