#!/bin/bash
set -e

if [ $# -ne 2 ]; then
    echo "Set a configuration property's value"
    echo "Usage: $0 <key> <value>"
    exit 1
fi

# Convert newlines to '\\n'. See http://stackoverflow.com/a/1252191.
V=$(echo "$2" | sed ':a;N;$!ba;s/\n/\\n/g')

DEPLOYMENT_SECRET=$(cat /data/deployment_secret)

curl -XPOST --fail --silent --show-error \
     --header "Authorization: Aero-Service-Shared-Secret container-scripts $DEPLOYMENT_SECRET" \
     --data-urlencode "key=$1" --data-urlencode "value=${V}" \
     config.service:5434/set
