#!/bin/bash

for i in "$@"; do
    if [ x`echo $i | grep :` != x ]; then
        if [ x"$HOST" != x ]; then
            echo "$0: too many hosts" >&2
            exit 1
        fi
        HOST=`echo $i | sed -e 's/:.*//' | sed -e 's/.*@//'`
    fi
done

if [ x"$HOST" != x ]; then
    fwknop -A tcp/22 -D $HOST -s --get-key `dirname $0`/fwknop.key > /dev/null
fi

scp "$@"
