#!/bin/bash

for i in "$@"; do
    # use "." to identify hostnames, which is not 100% reliable though
    if [ x`echo $i | grep '\.'` != x ]; then
        HOST=`echo $i | sed -e 's/:.*//' | sed -e 's/.*@//'`
        break
    fi
done

fwknop -A tcp/22 -D "$HOST" -s --get-key `dirname $0`/fwknop.key > /dev/null
ssh "$@"
