
# The official image hasn't picked up the recent commit
# for MYSQL_ALLOW_EMPTY_PASSWORD yet.
# FROM mysql:5.6
FROM weihan/mysql:5.6

MAINTAINER Weihan Wang "weihan@aerofs.com"

ENV MYSQL_ALLOW_EMPTY_PASSWORD 1
