#!/usr/bin/env bash

PWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

s3cmd sync --cf-invalidate --acl-public --delete-removed --no-mime-magic --guess-mime-type "$PWD/web/static/" s3://aerofs.admin_panel/
