#!/bin/sh

readonly ERRBADARGS=17
readonly ERRBADMODE=18

#
# usage:
#   abspath [path]
#
# parameters:
#   [path]: any path for which to get the absolute path
#
# example:
#   abspath ~
#
function abspath() {
    [[ "$1" = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

#
# usage:
#   to_lower [string]
#
# parameters:
#   [string]: any ascii string to convert to lowercase
#
# example:
#   to_lower HELLO_WORLD
#
function to_lower() {
     echo "$1" | tr '[A-Z]' '[a-z]'
}
