#!/bin/bash
set -eu

if [ $# -lt 1 ]
then
    echo "Usage: deactivate-users <user1> [<user2> <user3> ...]"
    exit 1
fi

function normalize()
{
    echo $@ | sed 's/@/_/g' | sed 's/\./_/g' | sed 's/-/_/g' | sed 's/+/_/g'
}

user_ids=$@
cd $(dirname $0)/..

echo ">> Building supporting Java code..."
gradle src/support:build src/support:dist

echo ">> Populate CA certificate..."
cp resource/common/mode/public/cacert.pem out.gradle/support/dist

echo ">> Acquiring new password hashes..."
cd out.gradle/support/dist

for user_id in $user_ids
do
    echo ">>> Get hash for $user_id"
    h=$(java -cp aerofs-support.jar com.aerofs.support.tools.GetHashedPassword "$user_id" "__deleted_by_support__")
    normal=$(normalize $user_id)
    declare hash_$normal="$h"
done

echo ">> Run the following commands on sp.aerofs.com as root."
echo ">> N.B. this will disable the user's second factor! (required for deactivation)"
echo ">> Press ENTER when finished."
echo
for user_id in $user_ids
do
    normal=$(normalize $user_id)
    h="hash_$normal"
    echo "mysql aerofs_sp -e \"update sp_user set u_hashed_passwd='${!h}', u_two_factor_enforced=0 where u_id='$user_id'\""
done
echo
read enter

echo -n ">> Last chance: are you sure you would like to deactivate these users? [y/n] "
read yn

if [ "$yn" != "y" ]
then
    echo ">> Deactivation aborted."
    exit 0
fi

echo ">> Performing deactivation..."
for user_id in $user_ids
do
    echo ">>> Deactivate $user_id"
    java -cp aerofs-support.jar com.aerofs.support.tools.DeactivateUser "$user_id" "__deleted_by_support__" || true
done

echo ">> Done."
