#!/bin/bash
set -eu

if [ $# -ne 1 ]
then
    echo "Usage: deactivate-user <user_id>"
    exit 1
fi

user_id=$1
cd $(dirname $0)/..

echo ">> Building supporting Java code..."
ant package_support -Dmode=PUBLIC 1>/dev/null 2>/dev/null

echo ">> Populate CA certificate..."
cp resource/common/mode/public/cacert.pem out.ant/artifacts/deactivate-user

echo ">> Acquiring new password hash..."
cd out.ant/artifacts/get-hashed-password
hash=$(java -jar get-hashed-password.jar "$user_id" "__deleted_by_support__")
cd ../../..

echo ">> Run the following command on sp.aerofs.com as root."
echo ">> N.B. this will disable the user's second factor! (required for deletion)"
echo ">> Press ENTER when finished."
echo "mysql aerofs_sp -e \"update sp_user set u_hashed_passwd='$hash', u_two_factor_enforced=0 where u_id='$user_id'\""
read enter

echo -n ">> Last chance: are you sure you would like to deactivate this user? [y/n] "
read yn

if [ "$yn" != "y" ]
then
    echo ">> Deactivation aborted."
    exit 0
fi

echo ">> Performing deactivation..."
cd out.ant/artifacts/deactivate-user
java -jar deactivate-user.jar "$user_id" "__deleted_by_support__"
cd ../../..

echo ">> Done. User $user_id has been deactivated."
