#!/bin/bash -u -e
# This script retrives a defect and retraces it; it infers what the version number should be

if [ $# -ne 1 ]; then
    echo "Usage: $0 <defect_number>"
    echo
    echo "Example: $0 370499"
    exit 1
fi

echo "Inferring version number via c.aerofs.com..."
DEFECT="$1"
VER=$( ssh c.aerofs.com "getver $DEFECT" )

if [ x"$VER" == "x" ]; then
    echo "No version for defect!"
    exit 1
else
    echo "Defect has client version $VER"
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
"$SCRIPT_DIR"/retrace_helper.py get-defects $VER $DEFECT
