#!/bin/sh
#
# Find all the busy threads from CPU samplings submitted by the users.
# When a user submits a problem report with keyword "cpu", submitted logs
# will contain stack trace sampling. This script prints out all the
# busy threads found in logs for a given defect number. The defect logs
# must have been downloaded to the current working directory using the
# getdefect script.

if [ $# -ne 1 ]
then
    echo "Usage: $0 <defect_number>"
    exit 1
fi

for i in daemon gui; do
    echo $i.log:

    grep -A 1 RUNNABLE defect-$1/$i.log | \
        grep -v KQueueArrayWrapper.kevent0 | \
        grep -v UNIXProcess.waitForProcessExit | \
        grep -v org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool | \
        grep -v JNotify_macosx.nativeNotifyLoop | \
        grep -v RUNNABLE | \
        grep -v WindowsSelectorImpl | \
        grep -v socketAccept | \
        grep -v socketRead | \
        grep -v receive  | \
        grep -v XmppMain_run | \
        grep -v getStackTrace | \
        grep -v WaitMessage | \
        grep -v PeekMessageW | \
        grep -v discard | \
        grep -v socketConnect | \
        grep -v -- -- | \
        grep -v "^[[:space:]]*$"
done
