#!/bin/bash

PACKAGES="aerofs-installer.deb \
    aerofsts-installer.deb \
    AeroFSTeamServerInstall.dmg \
    AeroFSInstall.dmg \
    AeroFSTeamServerInstall.exe \
    AeroFSInstall.exe"

for package in $PACKAGES
do
    wget http://nocache.client.ci.aerofs.com/$package
done
