#!/bin/bash
# This script retrives defect log files and retrace them
set -eu

if [ $# -eq 0 ]; then
    echo "usage: $0 [defect # (multiple, space separated)]"
    echo
    echo "example: $0 ff8b799e-75dd-4f71-ac72-48a61cad9f0an"
    exit 1
fi

DEFECTS="$@"

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

retrace()
{
    FOLDER=$1
    PROGRAM=$2
    ${BASE}/retrace_v2.py rl "$FOLDER/$PROGRAM.log"
}

main()
{
    for DEFECT in $DEFECTS; do
        TARGET_FOLDER="defect-$DEFECT" # puts this into the pwd
        if [[ -e "$TARGET_FOLDER" ]]; then
            echo "$TARGET_FOLDER already exists"
            continue
        fi

        scp -r dryad.aerofs.com:/data/defects/$DEFECT $TARGET_FOLDER

        for file in "$TARGET_FOLDER"/*.zip
        do
            echo $file
            typeset destdir=${file%%.zip}
            mkdir -p $destdir ||:
            unzip -o "$file" -d "$destdir"
            rm $file

            echo "Retracing logs for $DEFECT"

            for i in daemon cli gui; do
                if [ -f "$destdir/$i.log" ]; then
                    retrace "$destdir" $i
                fi
            done

            if [ ! -z "$(ls $destdir/name*map 2>/dev/null)" ]
            then
                echo "Reverse crc logs for $DEFECT"

                for i in daemon cli gui; do
                    if [ -f "$destdir/$i.log" ]; then
                        mv "$destdir/$i.log" "$destdir/unmapped.$i.log"

                        cat "$destdir/unmapped.$i.log" | \
                            ${BASE}/reverse-crc/reverse-crc.py -f $(ls "$destdir/name"*"map") > \
                            "$destdir/$i.log"
                    fi
                done
            fi

            rm -f "$destdir/obfuscated"*
            rm -f "$destdir/unmapped"*
            rm -f "$destdir/name"*"map"
        done
    done

    echo "Done"
}

main
