#!/bin/sh

MODE="$1"
VER="$2"
DIR="$3"

if [ ! "$#" -eq "3" ]; then
  echo "usage: $0 public|private [version] [dir_to_save_the_file]"
  exit 1
fi

FILE="aerofs-$VER-$MODE.map"
MAP_FILE="$DIR"/"$FILE"

if [ ! -f "$MAP_FILE" ]; then
    echo "retrieving $FILE..."
    scp sv.aerofs.com:/maps/"$FILE" "$MAP_FILE"
fi
