#!/bin/bash

# check number of arguments

NUM_ARGS=1 # 1) LINUX, WIN, MAC

if [ $# -ne $NUM_ARGS ]
then
    echo "Usage: `basename $0` LINUX|MAC|WIN"
    exit 1
fi

# check for the exact url

URL="https://www.aerofs.com/downloads/"

# check for the platform type

LINUX_PKG_NAME=aerofs-installer.deb
WIN_PKG_NAME=AeroFSInstall.exe
MAC_PKG_NAME=AeroFSInstall.dmg

case "$1" in
LINUX) URL="$URL$LINUX_PKG_NAME"
       ;;
MAC)   URL="$URL$MAC_PKG_NAME"
       ;;
WIN)   URL="$URL$WIN_PKG_NAME"
       ;;
*)     echo "Bad platform name"
       exit 1
       ;;
esac

# download the package

echo
echo "================================================================================"
echo
echo "Downloading installation package for $1 ..."
echo
echo "================================================================================"
echo

wget --no-check-certificate $URL
