#!/bin/bash -e
# This script retrives defect log files and retrace them

source common #for abspath()

if [ $# -lt 2 ]; then
    echo "usage: $0 [prod version] [defect # (multiple, space separated)]"
    echo
    echo "example: $0 0.2.37 6308 6310 6317"
    exit 1
fi

VER="$1"
shift # remove the first argument
DEFECTS="$@"

BASE=`dirname $0`
BASE=`abspath "$BASE"`
MAP_FILE="$BASE"/"aerofs-$VER-prod.map"

$BASE/getmap $VER $BASE

SED_SCRIPT_1='s/^	/	at /g'
SED_SCRIPT_2='s/at at/at/g'

for DEFECT in $DEFECTS; do
    TARGET_FOLDER="defect-$DEFECT" # puts this into the pwd
    if [[ -e "$TARGET_FOLDER" ]]; then
        echo "$TARGET_FOLDER already exists"
        continue
    fi
    ZIP_FILE="log.defect-$DEFECT.zip"
    kscp sp.aerofs.com:/var/svlogs_prod/defect/"$ZIP_FILE" .
    mkdir "$TARGET_FOLDER"
    unzip -o "$ZIP_FILE" -d "$TARGET_FOLDER"
    rm "$ZIP_FILE"

    echo "Unobfuscating logs for $DEFECT"

    sed -i "" "$SED_SCRIPT_1" "$TARGET_FOLDER/daemon.log"
    sed -i "" "$SED_SCRIPT_2" "$TARGET_FOLDER/daemon.log"
    sed -i "" "$SED_SCRIPT_1" "$TARGET_FOLDER/gui.log"
    sed -i "" "$SED_SCRIPT_2" "$TARGET_FOLDER/gui.log"

    mv "$TARGET_FOLDER/daemon.log" "$TARGET_FOLDER/obfuscated.daemon.log"
    mv "$TARGET_FOLDER/gui.log" "$TARGET_FOLDER/obfuscated.gui.log"

    ${BASE}/proguard/bin/retrace.sh "$MAP_FILE" "$TARGET_FOLDER/obfuscated.daemon.log" > "$TARGET_FOLDER/daemon.log"
    ${BASE}/proguard/bin/retrace.sh "$MAP_FILE" "$TARGET_FOLDER/obfuscated.gui.log" > "$TARGET_FOLDER/gui.log"
done

echo "Done"
