#!/bin/bash

if [ x"$1" == x ]; then
    echo "usage: $0 <inviter_email_address> <invitee_email_address>"
    exit
fi

ARG="--no-check-certificate"

INVITER=`echo $1 | sed -e 's/+/%2B/g'`
INVITEE=`echo $2 | sed -e 's/+/%2B/g'`

URL="https://staging.aerofs.com/sp/sp?aerofs=love&inviter=$INVITER&invitee=$INVITEE"
INVITE_RESPONSE=$( wget -q $ARG -O- "$URL" )
if [ $? != 0 ]; then
    echo "request failed. try the following URL manually to debug the problem:"
    echo "    $URL"
else
    ALREADY_EXIST=$( echo "$INVITE_RESPONSE" | grep 'ExAlreadyExist' )
    if [ $? != 0 ]; then
        SED_INVITE_CODE_EXPRESSION='s/.*code: //g'
        INVITE_CODE=$( echo "$INVITE_RESPONSE" | sed "$SED_INVITE_CODE_EXPRESSION" )
        echo "use this url to sign up the user: https://my-staging.aerofs.com/signup?c=$INVITE_CODE"
    else
        echo "$2 already exists"
    fi
fi
