#!/bin/bash

if [ x"$1" == x ]; then
    echo "usage: $0 <inviter_email_address> <invitee_email_address>"
    exit
fi

ARG="--no-check-certificate"

INVITER=`echo $1 | sed -e 's/+/%2B/g'`
INVITEE=`echo $2 | sed -e 's/+/%2B/g'`

url="https://staging.aerofs.com/sp/sp?aerofs=love&inviter=$INVITER&invitee=$INVITEE"
wget -q $ARG -O- "$url"
if [ $? != 0 ]; then
    echo request failed. try the following URL manually to debug the problem:
    echo "    $url"
fi
