#!/bin/sh
#
# Usage:
#        $ ./retrace <version> <<end
#        (paste obfuscated stack trace here as "heredoc")
#        end
#

VER=$1

if [ x"$VER" == x ]; then
    echo "usage: $0 <VER>"
    exit 1
fi

# the following block is idential to the block in the 'getdefects' script
function abspath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
BASE=`dirname $0`
BASE=`abspath "$BASE"` # needed by proguard's retrace.sh
FILE=aerofs-$VER-prod.map
LOCAL_FILE="$BASE/$FILE"
if [ ! -f "$LOCAL_FILE" ]; then
    echo "retrieving map file..."
    kscp release-staging@b.arrowfs.org:/home/release-prod/"$FILE" "$LOCAL_FILE"
fi

cd "$BASE"/proguard
bin/retrace.sh "$LOCAL_FILE"
