#!/bin/sh
#
# Usage:
#        $ ./retrace <version> <<end
#        (paste obfuscated stack trace here as "heredoc")
#        end
#

BASE=$(dirname "$0")
source "$BASE"/common #for abspath()

BASE=$(abspath "$BASE") # needed by proguard's retrace.sh

VER=$1

if [ x"$VER" == x ]; then
    echo "usage: $0 <VER>"
    exit 1
fi

MAP_FILE="$BASE/aerofs-$VER-public.map"
"$BASE"/get-map $VER $BASE
cd "$BASE"/proguard
bin/retrace.sh "$MAP_FILE"
