"""
File to hold all constants related to the inception project apps. All the
/mnt/share/ files are generated by the web bootstrap program.

Constants like timeouts, etc., are not included in this file. Only stuff
related to network ports and filenames/directories.
"""

"""
Network ports
"""

# KVMs manager application server port.
KVMS_SRV_PORT = 64790

# KVMs manager application client port.
KVMS_CLT_PORT = 64789

# VM hosts manager application server port.
VMHOSTS_SRV_PORT = 64791

# VM hosts manager application client port.
VMHOSTS_CLT_PORT = 64792

"""
Config files - Common
"""

# Certificate and private key.
CERT_KEY_FILE = '/mnt/share/.config/cert.pem'

# The log file for both the VM host Manager and the KVM Manager.
LOG_FILE = '/var/log/aerofs.log'

"""
Config files - KVM
"""

# File holding the hostname/IP of the parent VM.
VMHOST_ADDR_FILE = '/mnt/share/.config/vmhost.addr'

# File that holds the name of the KVM service.
KVM_SERVICE_FILE = '/mnt/share/.config/service.name'

"""
Config files - VM host
"""

# File holding the hostname/IP of the admin panel server.
ADMIN_ADDR_FILE = '/mnt/share/.config/admin.addr'

# The unique ID file generated during bootstrap.
VMHOST_ID_FILE = '/mnt/share/.config/vmhost.id'

# Autostart directory (used in the kvm class).
AUTOSTART_DIR = '/etc/libvirt/qemu/autostart'

# Directory where KVM images are stored.
KVM_IMG_DIR = '/root/images'
