name    'aerofs-webadmin'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'admin panel for aerofs'
description 'admin panel for aerofs'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
