name    'aerofs-pagerduty'
version '0.0.1'
source 'UNKNOWN'
author 'aerofs'
license 'Apache License, Version 2.0'
summary 'Pagerduty package and configuration'
description 'Pagerduty package and configuration'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
