name    'aerofs-fwknop'
version '0.0.1'
source 'UNKNOWN'
author 'AeroFS'
license 'Apache License, Version 2.0'
summary 'install and configure fwknop'
description 'install and configure fwknop server'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
