#!/bin/bash

email_default=team@aerofs.com
days_default=7

usage()
{
    if [ ! -z "$@" ]
    then
        echo "ERROR: $@"
    fi

    echo "Usage: $0 [options] <crt_filename>"
    echo "Available options:"
    echo " -e <email_address> Email address for stale crt notification. [default=$email_default]"
    echo " -d <days>          Certificate expiration interval (eg. if cert_date < days). [default=$days_default]"
    echo " -n                 Do not send an email notification."
    echo " -h                 Display this help message."
}

email=$email_default
do_email=1
days=$days_default

while getopts "d:e:nh" opt
do
    case $opt in
        e)
            email="${OPTARG}"
            if [ -z "$email" ]
            then
                usage "invalid null email address"
                exit 1
            fi
            ;;
        d)
            days="${OPTARG}"
            if ! [[ "$days" =~ ^[0-9]+$ ]]
            then
                usage "invalid number of days"
                exit 1
            fi
            ;;
        n)
            do_email=0
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

shift $(($OPTIND - 1))
crt_filename=$@

if [ -z "$crt_filename" ]
then
    usage
    exit 1
fi

if [ ! -f "$crt_filename" ]
then
    echo "ERROR: cannot find crt file \"$crt_filename\""
    exit 1
fi

# Pull the date from the certificate.
openssl_data=$(openssl x509 -noout -in $crt_filename -dates 2>/dev/null)

if [ $? -ne 0 ]
then
    echo "OpenSSL Error. Aborting."
    exit 1
fi

expire_string=$(echo "$openssl_data" | grep -i "notafter" | awk -F= '{print $2}')
expire=$(date -d "$expire_string" -u "+%s")

now=$(date "+%s")
diff=$[$expire-$now]
diff_days=$[$diff/60/60/24]

msg=""

if [ $diff -lt 0 ]
then
    msg="ERROR: $crt_filename is expired!"
elif [ $diff_days -lt $days ]
then
    msg="WARNING: $crt_filename will expire in $diff_days days! (expires on $expire_string)."
fi

if [ ! -z "$msg" ]
then
    echo $msg

    if [ $do_email -eq 1 ]
    then
        echo "Sending email notification."
        echo $msg | mail -s "Certificate Expiration Notice $(hostname | tr 'a-z' 'A-Z')" $email

        if [ $? -ne 0 ]
        then
            echo "ERROR: unable to send email notification."
            exit 1
        fi
    fi
else
    echo "Certificate OK."
fi
