#!/bin/bash

#
# constants
#

PROD_STRING="PROD"

#
# check the number of arguments
#
# arg #1 server name arg # 2 (optional) PROD or STAGING
#

EXPECTED_ARGS=1
if [ $# -ne $EXPECTED_ARGS ]
then
	echo "usage: `basename $0` [server_name] <PROD|STAGING (default = STAGING)>"
	exit 1
fi

#
# enter PROD or staging mode
#

PROD=0
if [ $# -eq 2 ] && [ "$2" -eq "$PROD_STRING" ]
then
	PROD=1
fi

#
# print preamble
#

SERVER_NAME=
if [ $PROD -eq 1 ]
then
	SERVER_NAME="$1"

	echo
	echo "generating PROD cert for $SERVER_NAME"
else
	SERVER_NAME="$1""-staging"

	echo
	echo "generating STAGING cert for $SERVER_NAME"
fi


#
# -----------------------------------------------------------------------------
#
# Filename constants
#
# -----------------------------------------------------------------------------
#

SERVER_OPENSSL_PCKS1_KEY_FILENAME="$SERVER_NAME"".openssl.key" # pem
SERVER_CSR_FILENAME="$SERVER_NAME"".csr"                       # pem, pcks10
SERVER_PKCS8_KEY_FILENAME="$SERVER_NAME"".key"                 # pem
SERVER_X509CERT_FILENAME="$SERVER_NAME"".crt"                  # pem

#
# -----------------------------------------------------------------------------
#
#
#
# -----------------------------------------------------------------------------
#

#
# create output directory
#

echo
echo "creating dir for server keys and certs"
echo "--------------------------------------"

SERVER_SSL_DIR="$SERVER_NAME""_ssl"

rm -rf $SERVER_SSL_DIR
mkdir $SERVER_SSL_DIR
cd $SERVER_SSL_DIR

#
# create keypair
#

echo
echo "generating unsecured key pair"
echo "-----------------------------"
echo

openssl genrsa -out "$SERVER_OPENSSL_PCKS1_KEY_FILENAME" 1024
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in "$SERVER_OPENSSL_PCKS1_KEY_FILENAME" -out "$SERVER_PKCS8_KEY_FILENAME"

#
# create csr
#

echo
echo "generating csr"
echo "--------------"

openssl req -new -key "$SERVER_PKCS8_KEY_FILENAME" -out "$SERVER_CSR_FILENAME" -subj "/C=US/ST=CA/L=SF/O=aerofs.com/OU=na/CN=$SERVER_NAME.aerofs.com"

#
# sign the cert ourself
#

echo
echo "creating self-signed certificate"
echo "--------------------------------"

openssl x509 -req -days 365 -in "$SERVER_CSR_FILENAME" -signkey "$SERVER_PKCS8_KEY_FILENAME" -out "$SERVER_X509CERT_FILENAME"

#
# check if the file was created
#

CERTIFICATE_STRING='-----BEGIN CERTIFICATE-----'

# IMPORTANT: use double dash prevent our repeated dashes from being interpreted as options
if grep -xq -- "$CERTIFICATE_STRING" "$SERVER_X509CERT_FILENAME"
then
	echo
	echo "certificate created successfully!"
	echo
else
	echo
	echo "certificate not created!"
	echo
fi
