#!/bin/bash

#
# constants
#

PROD_CA_URL="http://joan.aerofs.com:1029/prod"
STAGING_CA_URL="http://joan-staging.aerofs.com:1029/staging"
PROD_STRING="PROD"

#
# check the number of arguments
#
# arg #1 server name arg #2 (optional) PROD or STAGING
#

EXPECTED_ARGS=1
if [ $# -lt $EXPECTED_ARGS ]
then
	echo "usage: `basename $0` [server_name] <PROD|STAGING (default = STAGING)>"
	exit 1
fi

#
# enter PROD or staging mode
#

PROD=0
if [ $# -eq 2 ] && [ "$2" == "$PROD_STRING" ]
then
	PROD=1
fi

#
# print preamble
#

SERVER_NAME=
CA_URL=
if [ $PROD -eq 1 ]
then
	SERVER_NAME="$1"
	CA_URL="$PROD_CA_URL"

	echo
	echo "Revoking PROD cert for $SERVER_NAME via $CA_URL"
else
	SERVER_NAME="$1""-staging"
	CA_URL="$STAGING_CA_URL"

	echo
	echo "Revoking STAGING cert for $SERVER_NAME via $CA_URL"
fi

#
# perform the certificate revocation.
#

rm -f revoke.txt
curl --silent --output revoke.txt "$CA_URL""?revokecert=""$SERVER_NAME.aerofs.com"

#
# check if the file was created
#

if ! [ -f revoke.txt ] || [ "$(cat revoke.txt)" != "200 OK" ]
then
	echo
	echo "Certificate not revoked!"
	echo
else
	echo
	echo "Certificate revoked successfully!"
	echo
fi
